### ISSUE TITLE
Support for Apple Silicon's ARM64 architecture

### ISSUE THREAD

**Issue by jamiesauve** [discordjs/opus#72] opened 2021-03-12 02:04 UTC
**Is your feature request related to a problem? Please describe.**
I've built a custom bot that uses this package, and it has worked great. I just got a Mac Mini M1 and was sad to see that the bot doesn't work anymore. 

**Describe the ideal solution**
I see on your page that Apple Silicon isn't supported - are you planning to add support for it? If so, do you have a rough estimate of the timeline?

**Describe alternatives you've considered**
I can look into other packages I could use to build the bot - I may do that if it's likely to be a while, but I'd like to keep using this if possible.

**Additional context**
```
➜  npm i
npm ERR! code 1
npm ERR! path [...] /node_modules/@discordjs/opus
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build

node -v
v15.11.0
```

**Comment by xAtsuUC** [comment] 2021-03-12 04:11
See [this](https://github.com/johnpapa/generator-hottowel/issues/134#issuecomment-217490413) issue comment, it may help

**Comment by iCrawl** [comment] 2021-03-12 09:07
I don't see how ARM64 is not supported.

First is that error message very bare bones and does not indicate at all that M1 isn't supported.

But feel free to do the following steps:
```sh
sudo apt-get update
sudo apt-get install autoconf
sudo apt-get install libtool
cd deps/opus
./autogen.sh
./configure --enable-static --disable-shared --with-pic
mkdir -p ../config/opus/[os]/[arch]
cp config.h ../config/opus/[os]/[arch]
```

First three steps vary probably, since this is macOS

**Comment by belcar-s** [comment] 2021-03-22 14:50
`autogen.sh` does not exist in my copy.

**Comment by jamiesauve** [comment] 2021-04-12 23:31
Sorry, got distracted and totally spaced this 😬 

I'm not sure that ARM64 is the problem - the bot I wrote runs fine on Mac with x64 architecture but doesn't on the ARM64 one. I'm not sure what else would have changed it but it certainly could be something else (like npm).

What do the steps you provided above do? Trying to piece it together for mac. Is that globally installing `autoconf` and `libtool`? Can I do something similar with npm? I'm using JavaScript.

**Comment by tipakA** [comment] 2021-04-12 23:59
No, `npm` does not install system applications or libraries. The closest for mac would probably be `brew`, and it seems like both `autoconf` and `libtool` are on there.

**Comment by weaversam8** [comment] 2021-05-12 19:29
I can confirm this library still doesn't compile correctly on ARM64 M1 Macs.

I've compiled and installed `libopus` per the instructions in [their README](https://gitlab.xiph.org/xiph/opus/-/blob/v1.3.1/README), but I still get the following error when installing from `node-gyp`.

```
[... logs truncated ...]

  CC(target) Release/obj.target/libopus/deps/opus/src/opus_multistream.o
../deps/opus/src/opus_multistream.c:29:10: fatal error: 'config.h' file not found
#include "config.h"
         ^~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/libopus/deps/opus/src/opus_multistream.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/weaver/.nvm/versions/node/v15.13.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:369:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Darwin 20.4.0
gyp ERR! command "/Users/weaver/.nvm/versions/node/v15.13.0/bin/node" "/Users/weaver/.nvm/versions/node/v15.13.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/weaver/Documents/Git/@discordjs-opus/prebuild/node-v88-napi-v3-darwin-arm64-unknown-unknown/opus.node" "--module_name=opus" "--module_path=/Users/weaver/Documents/Git/@discordjs-opus/prebuild/node-v88-napi-v3-darwin-arm64-unknown-unknown" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3"
gyp ERR! cwd /Users/weaver/Documents/Git/@discordjs-opus
gyp ERR! node -v v15.13.0
gyp ERR! node-gyp -v v7.1.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/weaver/.nvm/versions/node/v15.13.0/bin/node /Users/weaver/.nvm/versions/node/v15.13.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/weaver/Documents/Git/@discordjs-opus/prebuild/node-v88-napi-v3-darwin-arm64-unknown-unknown/opus.node --module_name=opus --module_path=/Users/weaver/Documents/Git/@discordjs-opus/prebuild/node-v88-napi-v3-darwin-arm64-unknown-unknown --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/weaver/Documents/Git/@discordjs-opus/node_modules/@discordjs/node-pre-gyp/lib/util/compile.js:85:20)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:369:20)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1067:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
node-pre-gyp ERR! System Darwin 20.4.0
node-pre-gyp ERR! command "/Users/weaver/.nvm/versions/node/v15.13.0/bin/node" "/Users/weaver/Documents/Git/@discordjs-opus/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/weaver/Documents/Git/@discordjs-opus
node-pre-gyp ERR! node -v v15.13.0
node-pre-gyp ERR! node-pre-gyp -v v0.3.2
node-pre-gyp ERR! not ok 
Failed to execute '/Users/weaver/.nvm/versions/node/v15.13.0/bin/node /Users/weaver/.nvm/versions/node/v15.13.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/weaver/Documents/Git/@discordjs-opus/prebuild/node-v88-napi-v3-darwin-arm64-unknown-unknown/opus.node --module_name=opus --module_path=/Users/weaver/Documents/Git/@discordjs-opus/prebuild/node-v88-napi-v3-darwin-arm64-unknown-unknown --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
npm ERR! code 1
npm ERR! path /Users/weaver/Documents/Git/@discordjs-opus
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/weaver/.npm/_logs/2021-05-12T19_28_16_510Z-debug.log
```

**Comment by bossanovaorca** [comment] 2021-06-19 13:43
are there any updates or workaround for this issue? I'm unable to install the package on Darwin ARM64

**Comment by bossanovaorca** [comment] 2021-07-01 07:19
will this be resolved by https://github.com/discordjs/opus/pull/76?

**Comment by kyranet** [comment] 2021-08-18 09:46
https://github.com/discordjs/opus/releases/tag/v0.6.0 has been released with support for this 👍🏼

**Closed** 2021-08-18 09:46 UTC
Labels: feature request
