### ISSUE TITLE
Missing dependency "node-pre-gyp"

### ISSUE THREAD

**Issue by pigulla** [discordjs/opus#16] opened 2020-05-03 12:59 UTC
**Please describe the problem you are having in as much detail as possible:**
The module can not be loaded after installation.

**Include a reproducible code sample here, if possible:**

```bash
npm i @discordjs/opus && node --eval 'require("@discordjs/opus");'
```

**Further details:**
Fails with:
```
Error: Cannot find module 'node-pre-gyp'
```

- @discordjs/opus version: 0.3.1
- Node.js version: 14 (same issue with 12)
- Operating system: Debian 10
- Priority this issue should have – please be realistic and elaborate if possible: low - it can be worked around by manually installing `node-pre-gyp`

**Comment by iCrawl** [comment] 2020-05-03 14:56
Duplicate of #15

**Closed by iCrawl** 2020-05-03 14:56 UTC
Labels: bug
